repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: CHANGELOG.md
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
        exclude: /template/
    -   id: debug-statements
    -   id: name-tests-test
        args: [--django]
    -   id: requirements-txt-fixer
    -   id: fix-encoding-pragma
        args: [--remove]
