---
language: ruby
rvm:
  - 2.4.1

services:
  - docker

before_script:
  - sudo pip install ansible-lint yamllint

script:
  - ansible-lint -c ./test/lint/.ansible-lint .
  - yamllint --config-file ./test/lint/yaml-lint.yml .
  - bundle exec kitchen test install-source --concurrency
