---
driver:
  name: vagrant

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbosity: 2
  ansible_verbose: true

verifier:
  name: inspec

platforms:
  # Redhat
  # - name: centos-6
  # - name: centos-7
  # - name: fedora-28
  # - name: fedora-29
  # Debian
  - name: debian-8
  - name: debian-9
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: install_package
    provisioner:
      playbook: test/integration/install_package/install_package.yml
  - name: install_source
    provisioner:
      playbook: test/integration/install_source/install_source.yml