---
driver:
  name: vagrant

transport:
  # TODO: remove with better solution than workaround:
  # https://github.com/test-kitchen/test-kitchen/issues/1035
  max_ssh_sessions: 6

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbosity: 2
  ansible_verbose: true

verifier:
  name: inspec

platforms:
  # Redhat
  - name: centos-7
  - name: fedora-28
  - name: fedora-29
  # Debian
  - name: debian-8
  - name: debian-9
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: install_package
    provisioner:
      playbook: test/integration/install/install_package/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/install/install_package
    excludes:
      # redhat & debian OS system packages are not available
      # see: https://geth.ethereum.org/install-and-build/Installing-Geth
      - centos-7
      - fedora-28
      - fedora-29
      - debian-8
      - debian-9

  - name: install_source
    provisioner:
      playbook: test/integration/install/install_source/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/install/install_source

  - name: default_config
    provisioner:
      playbook: test/integration/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/config/default

  - name: default_service
    provisioner:
      playbook: test/integration/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/service/default
