---

- hosts: linux
  vars:
      install_type: source  
  tasks:
    - name: Include OS-specific variables.
      include_vars:
        file: "../vars/{{ ansible_os_family|lower }}.yml"

    - name: Include common installation tasks
      include_tasks: "common/install.yml"

    - name: Include OS-specific installation tasks
      include_tasks: "{{ ansible_os_family|lower }}/install.yml"
