---
- name: Include OS and distribution specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      skip: true

- name: Include common installation tasks
  include_tasks: "common/install.yml"

- name: Include OS and distribution specific installation tasks.
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution|lower }}/install.yml"
      - "{{ ansible_os_family|lower }}/install.yml"
      skip: true

- name: Render geth client toml configuration
  include_tasks: "common/config.yml"

- name: Start Geth client and RPC service
  include_tasks: "common/service.yml"
