---
- name: Include OS-specific variables.
  include_vars:
    file: "{{ ansible_os_family|lower }}.yml"
  when: ansible_os_family == "Darwin"

- name: Include common installation tasks
  include_tasks: "common/install.yml"

- name: Include OS-specific installation tasks
  include_tasks: "{{ ansible_os_family|lower }}/install.yml"

- name: Render geth client toml configuration
  include_tasks: "common/config.yml"

- name: Start Geth client and RPC service
  include_tasks: "common/service.yml"
