---

- name: Geth installation playbook
  hosts: test
  tasks:
  - name: Ensure Homebrew parent directory has correct permissions (MacOS < 10.13).
    file:
      path: "/usr/local"
      owner: root
      state: directory
  - name: Install geth homebrew package
    homebrew:
      name: ethereum
      state: present
    when: ansible_os_family == 'Darwin'
  - name: Add PPA for Ethereum
    apt_repository:
      repo: 'ppa:ethereum/ethereum'
      state: present
      update_cache: true
    become: true
    when: ansible_os_family != 'Darwin'
  - name: Install geth package
    package:
      name: ethereum
      state: present
    become: true
    when: ansible_os_family != 'Darwin'
