---
  #######  Package installation #######
- name: Tap ethereum formula repository
  homebrew_tap:
    name: ethereum/ethereum
    state: "{{ install_state }}"
  when: install_type == "package"

- name: Install geth homebrew package
  homebrew:
    name: ethereum
    state: "{{ install_state }}"
  when: install_type == "package"