---
- name: Restart geth service
  become: true
  when: not perform_uninstall and ansible_os_family|lower != 'darwin'
  service:
    name: geth
    state: restarted
  listen: Restart service
  ignore_errors: true

- name: Stop geth systemd service
  become: true
  when: ansible_os_family|lower != 'darwin'
  service:
    name: geth
    state: stopped
    enabled: false
  listen: Uninstall Geth

- name: Remove geth systemd service file
  become: true
  file:
    path: "{{ systemd_dir }}/geth.service"
    state: absent
  listen: Uninstall Geth

- name: Remove geth launchd service file
  become: true
  when: ansible_os_family|lower == 'darwin'
  file:
    path: "{{ launchd_dir }}/com.O1.geth.plist"
    state: absent
  listen: Uninstall Geth

- name: Uninstall geth service package
  become: true
  when: ansible_os_family|lower != 'darwin'
  package:
    name: ethereum
    state: absent
  listen: Uninstall Geth

- name: Uninstall geth homebrew-package
  become: true
  when: ansible_os_family|lower == 'darwin'
  homebrew:
    name: ethereum
    state: absent
  listen: Uninstall Geth

- name: Uninstall geth apt-repo
  become: true
  when: ansible_os_family|lower == 'debian'
  apt_repository:
    repo: 'ppa:ethereum/ethereum'
    state: absent
  listen: Uninstall Geth

- name: Uninstall geth homebrew-tap
  become: true
  when: ansible_os_family|lower == 'darwin'
  homebrew_tap:
    name: ethereum/ethereum
    state: absent
  listen: Uninstall Geth

- name: Remove geth install dir
  become: true
  file:
    path: "{{ install_dir }}"
    state: absent
  listen: Uninstall Geth

- name: Remove geth config dir
  become: true
  file:
    path: "{{ config_dir }}"
    state: absent
  listen: Uninstall Geth

- name: Remove geth data dir
  become: true
  file:
    path: "{{ geth_config.Node.DataDir }}"
    state: absent
  listen: Uninstall Geth

- name: Remove geth user
  become: true
  user:
    name: "{{ geth_user }}"
    state: absent
    remove: true
  listen: Uninstall Geth

- name: Remove geth group
  become: true
  group:
    name: "{{ geth_user }}"
    state: absent
  listen: Uninstall Geth
