---
- name: Restart geth service
  service:
    name: geth
    state: restarted
  listen: Restart service
  when: not perform_uninstall and ansible_os_family|lower != 'darwin'

- name: Uninstall geth apt-repo
  become: true
  apt_repository:
    repo: 'ppa:ethereum/ethereum'
    state: absent
  listen: Uninstall Geth
  when: ansible_os_family|lower == 'debian'

- name: Uninstall geth service package
  package:
    name: ethereum
    state: absent
  become: true
  listen: Uninstall Geth
  when: ansible_os_family|lower != 'darwin'

- name: Uninstall geth homebrew-tap
  homebrew_tap:
    name: ethereum/ethereum
    state: absent
  listen: Uninstall Geth
  when: ansible_os_family|lower == 'darwin'

- name: Uninstall geth homebrew-package
  homebrew:
    name: ethereum
    state: absent
  listen: Uninstall Geth
  when: ansible_os_family|lower == 'darwin'

- name: Remove geth install dir
  file:
    path: "{{ install_dir }}"
    state: absent
  become: true
  listen: Uninstall Geth

- name: Remove geth config dir
  file:
    path: "{{ config_dir }}"
    state: absent
  become: true
  listen: Uninstall Geth

- name: Remove geth data dir
  file:
    path: "{{ geth_config.Node.DataDir }}"
    state: absent
  become: true
  listen: Uninstall Geth

- name: Stop geth systemd service
  service:
    name: geth
    state: stopped
    enabled: false
  listen: Uninstall Geth
  when: ansible_os_family|lower != 'darwin'

- name: Remove geth systemd service file
  become: true
  file:
    path: "{{ systemd_dir }}/geth.service"
    state: absent
  listen: Uninstall Geth
  when: ansible_os_family|lower != 'darwin'

- name: Remove geth launchd service file
  file:
    path: "{{ launchd_dir }}/com.O1.geth.plist"
    state: absent
  become: true
  listen: Uninstall Geth
  when: ansible_os_family|lower == 'darwin'

- name: Remove geth user
  user:
    name: "{{ geth_user }}"
    state: absent
    remove: true
  listen: Uninstall Geth

- name: Remove geth group
  group:
    name: "{{ geth_user }}"
    state: absent
  listen: Uninstall Geth
