---
#######  Package installation #######
- name: Check install_type for unsupported package option
  fail:
    msg: "Geth installation by OS system package is not supported on {{ ansible_os_family }}!"
  when: install_type == "package" and ansible_os_family == "Debian" and ansible_distribution != "Ubuntu"

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  changed_when: false
  when: install_type == "package"

- name: Add PPA for Ethereum
  apt_repository:
    repo: 'ppa:ethereum/ethereum'
    state: "{{ install_state }}"
    update_cache: true
  become: true
  when: install_type == "package" and ansible_distribution == "Ubuntu"

- name: Install geth package
  package:
    name: ethereum
    state: "{{ install_state }}"
  become: true
  when: install_type == "package"