---
# Geth configuration rendering
- name: Create installation directory
  file:
    path: "{{ config_dir }}"
    state: directory
    owner: "{{ geth_user }}"
    group: "{{ geth_user }}"
  become: true

- name: Copy Geth configuration in place
  template:
    src: "{{ config_template }}"
    dest: "{{ config_dir }}/config.toml"
    owner: "{{ geth_user }}"
    group: "{{ geth_user }}"
    mode: 0644

- name: Create data directory
  file:
    path: "{{ data_dir }}"
    state: directory
    owner: "{{ geth_user }}"
    group: "{{ geth_user }}"
  become: true