---
# Geth configuration rendering
- name: Create configuration directory
  file:
    path: "{{ config_dir }}"
    state: directory
    owner: "{{ geth_user }}"
    group: "{{ geth_user }}"
  become: true

- name: Copy Geth configuration in place
  template:
    src: "{{ config_template }}"
    dest: "{{ config_dir }}/config.toml"
    owner: "{{ geth_user }}"
    group: "{{ geth_user }}"
    mode: 0644
  notify:
    - restart geth

- name: Ensure creation of data directory based on configuration
  file:
    path: "{{ geth_config.Node.DataDir }}"
    state: directory
    owner: "{{ geth_user }}"
    group: "{{ geth_user }}"
  become: true
  notify:
    - restart geth
