---
- name: Create configuration directory
  become: true
  file:
    path: "{{ config_dir }}"
    state: directory
    owner: "{{ geth_user }}"
    group: "{{ geth_user }}"
  tags:
    - config

- name: Copy Geth configuration in place
  become: true
  template:
    src: "{{ _config_template }}"
    dest: "{{ config_dir }}/config.toml"
    owner: "{{ geth_user }}"
    group: "{{ geth_user }}"
    mode: 0644
  when: geth_config is defined and geth_config.keys()|length > 0
  notify:
    - Restart service
  tags:
    - config

- name: Ensure creation of data directory based on configuration
  become: true
  file:
    path: "{{ geth_config.Node.DataDir }}"
    state: directory
    owner: "{{ geth_user }}"
    group: "{{ geth_user }}"
  when: geth_config.Node.DataDir is defined and geth_config.Node.DataDir|length > 0
  tags:
    - config
    - data
