---
#######  Authentication setup #######
- name: Ensure Geth group exists
  group:
    name: "{{ geth_user }}"
    state: present
  become: true
  
- name: Create Geth user
  user:
    comment: Geth client account
    name: "{{ geth_user }}"
    group: "{{ geth_user }}"
  become: true

- name: Create data directory
  file:
    path: "{{ data_dir }}"
    state: directory
    owner: "{{ geth_user }}"
    group: "{{ geth_user }}"
  become: true