---
- name: Setup Geth systemd unit
  include_role:
    name: 0x0i.systemd
  vars:
    unit_config:
      - name: geth
        Unit:
          Description: Geth - an Ethereum Go client
          Documentation: https://geth.ethereum.org/docs/
          Wants: network-online.target
          After: syslog.target network-online.target
        Service: "{{ default_service_unit | combine(custom_unit_properties) }}"
        Install:
          WantedBy: multi-user.target
  when: ansible_os_family != "Darwin" and manage_service

- name: Enable and start Geth service
  become: true
  service:
    name: geth
    state: started
    enabled: true
  when: ansible_os_family != "Darwin" and manage_service
  notify:
    - check systemd service uninstall

- name: Render Geth launchd service plist in place
  become: true
  template:
    src: "{{ launchd_template }}"
    dest: "{{ launchd_dir }}/com.O1.geth.plist"
  when: ansible_os_family == "Darwin" and manage_service
