---
- name: Include OS and distribution specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
      skip: true
  tags:
    - always

- name: Check for uninstall signal
  block:
    - name: Broadcast uninstall signal
      command: /bin/true
      notify: Uninstall Geth
      when: perform_uninstall
  always:
    - name: Flush handlers
      meta: flush_handlers
    - name: End play following uninstallation
      meta: end_play
  when: perform_uninstall

- name: Set unit [Service] configuration
  set_fact:
    _default_service_unit:
      ExecStart: "{{ install_dir }}/geth {% if geth_config %}--config {{ config_dir }}/config.toml{% endif %} {{ extra_run_args|join(' ') }}"
      User: "{{ geth_user }}"
      Group: "{{ geth_user }}"
      StandardOutput: journal
      StandardError: inherit
  when: ansible_os_family != "Darwin" and manage_service
  tags:
    - preflight
