---
- name: Set unit [Service] configuration
  set_fact:
    _default_service_unit:
      ExecStart: "{{ install_dir }}/geth {% if geth_config %}--config {{ config_dir }}/config.toml{% endif %} {{ extra_run_args }}"
      User: "{{ geth_user }}"
      Group: "{{ geth_user }}"
      StandardOutput: journal
      StandardError: inherit
  when: ansible_os_family != "Darwin" and manage_service
  tags:
    - preflight
