---
- name: Copy Geth systemd service file in place
  template:
    src: "{{ systemd_template }}"
    dest: "{{ systemd_dir }}/geth.service"
    owner: "root"
    group: "root"

- name: Enable and start Geth service
  service:
    name: geth
    pattern: "{{ install_dir }}/geth"
    state: started
    enabled: yes