---
#######  Systemd service setup #######

- name: Render Geth systemd service file in place
  template:
    src: "{{ systemd_template }}"
    dest: "{{ systemd_dir }}/geth.service"
    owner: "root"
    group: "root"
  become: true
  when: ansible_os_family != "Darwin" and manage_service
  notify:
    - check systemd service file uninstall

- name: Enable and start Geth service
  service:
    name: geth
    state: started
    enabled: true
  become: true
  when: ansible_os_family != "Darwin" and manage_service
  notify:
    - check systemd service uninstall

#######  Launchd service setup #######

- name: Render Geth launchd service plist in place
  template:
    src: "{{ launchd_template }}"
    dest: "{{ launchd_dir }}/com.O1.geth.plist"
  become: true
  when: ansible_os_family == "Darwin" and manage_service
